# SET UP

## CREAR EL ENTORNO PARA EL PROYECTO

## IMPORTAR PAQUETES

In [1]:
import os
import numpy as np
import pandas as pd

#Automcompletar rápido
%config IPCompleter.greedy=True

## CREAR EL DIRECTORIO DEL PROYECTO

In [3]:
raiz = 'C:/Users/Marius/EstructuraDirectorio/03_MACHINE_LEARNING/07_CASOS/'

nombre_dir = '03_RIESGOS'

### Crear el directorio y la estructura del proyecto

In [11]:
path = raiz + nombre_dir

# try:
#     os.mkdir(path)
#     os.mkdir(path + '/01_Documentos')
#     os.mkdir(path + '/02_Datos')
#     os.mkdir(path + '/02_Datos/01_Originales')
#     os.mkdir(path + '/02_Datos/02_Validacion')
#     os.mkdir(path + '/02_Datos/03_Trabajo')
#     os.mkdir(path + '/02_Datos/04_Caches')
#     os.mkdir(path + '/03_Notebooks')
#     os.mkdir(path + '/03_Notebooks/01_Funciones')
#     os.mkdir(path + '/03_Notebooks/02_Desarrollo')
#     os.mkdir(path + '/03_Notebooks/03_Sistema')
#     os.mkdir(path + '/04_Modelos')
#     os.mkdir(path + '/05_Resultados')
#     os.mkdir(path + '/09_Otros')
    
# except OSError:
#     print ("La creación del directorio %s ha fallado" % path)
# else:
#     print ("Se ha creado satisfactoriamente el directorio %s " % path)

### Situar el directorio de trabajo en el proyecto

In [12]:
os.chdir(path)

## CREAR LOS DATASETS INICIALES

### Importar los datos

In [13]:
nombre_fichero_datos = 'prestamos.csv'

ruta_completa = path + '/02_Datos/01_Originales/' + nombre_fichero_datos

In [14]:
datos = pd.read_csv(ruta_completa)
datos

,id_cliente,empleo,antigüedad_empleo,ingresos,ingresos_verificados,rating,dti,vivienda,num_hipotecas,num_lineas_credito,...,id_prestamo,descripcion,finalidad,principal,tipo_interes,num_cuotas,imp_cuota,imp_amortizado,estado,imp_recuperado
0,137387967,Hvac technician,3 years,54000.0,Source Verified,A,19.31,MORTGAGE,2.0,10.0,...,NaN,NaN,debt_consolidation,15000.0,7.21,36 months,464.60,2669.06,Current,0.00
1,4798121,"Target Promotions and Marketing,Inc",10+ years,65000.0,Not Verified,D,25.40,RENT,1.0,15.0,...,NaN,NaN,debt_consolidation,10000.0,17.77,36 months,360.38,6362.96,Charged Off,0.00
2,46641215,Banker,5 years,135000.0,Verified,A,14.68,RENT,0.0,19.0,...,NaN,NaN,debt_consolidation,24000.0,6.39,36 months,734.38,24000.00,Fully Paid,0.00
3,87998444,executive director,9 years,188000.0,Source Verified,B,11.69,MORTGAGE,3.0,15.0,...,NaN,NaN,credit_card,27000.0,8.99,60 months,560.35,12443.00,Current,0.00
4,132883631,Subsea Technician,7 years,125000.0,Source Verified,B,9.00,MORTGAGE,1.0,6.0,...,NaN,NaN,debt_consolidation,22000.0,10.90,36 months,719.22,22000.00,Fully Paid,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,51876926,Office Manager,10+ years,42000.0,Not Verified,C,20.85,MORTGAGE,6.0,9.0,...,NaN,NaN,debt_consolidation,8000.0,12.29,36 months,266.83,8000.00,Fully Paid,0.00
199996,121031962,Owner & President,6 years,111697.0,Verified,B,16.63,MORTGAGE,2.0,10.0,...,NaN,NaN,other,10000.0,9.44,36 months,320.05,4388.51,Current,0.00
199997,135641397,Sr. Field Engineer,10+ years,285000.0,Source Verified,D,6.02,MORTGAGE,3.0,9.0,...,NaN,NaN,small_business,30000.0,17.47,36 months,1076.62,5387.53,Current,0.00
199998,53664762,Attorney,8 years,168000.0,Source Verified,E,4.69,RENT,0.0,8.0,...,NaN,NaN,small_business,30050.0,18.25,60 months,767.17,2964.44,Charged Off,2750.88
199999,94394801,NaN,NaN,80000.0,Not Verified,C,31.49,MORTGAGE,1.0,9.0,...,NaN,NaN,debt_consolidation,10000.0,13.99,36 months,341.73,7096.40,Current,0.00

### Extraer y reservar el dataset de validación

In [15]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 25 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id_cliente                   200000 non-null  int64
 1   empleo                       185300 non-null  object
 2   antigüedad_empleo            187112 non-null  object
 3   ingresos                     200000 non-null  float64
 4   ingresos_verificados         200000 non-null  object
 5   rating                       200000 non-null  object
 6   dti                          199853 non-null  float64
 7   vivienda                     200000 non-null  object
 8   num_hipotecas                195595 non-null  float64
 9   num_lineas_credito           199997 non-null  float64
 10  porc_tarjetas_75p            193368 non-null  float64
 11  porc_uso_revolving           199846 non-null  float64
 12  num_cancelaciones_12meses    199988 non-null  float64
 13  num_derogatorios             199997 non-null  float64
 14  num_meses_desde_ult_retraso  97384 non-null   float64
 15  id_prestamo                  0 non-null       float64
 16  descripcion                  11113 non-null   object
 17  finalidad                    200000 non-null  object
 18  principal                    200000 non-null  float64
 19  tipo_interes                 200000 non-null  float64
 20  num_cuotas                   200000 non-null  object
 21  imp_cuota                    200000 non-null  float64
 22  imp_amortizado               200000 non-null  float64
 23  estado                       200000 non-null  object
 24  imp_recuperado               200000 non-null  float64
dtypes: float64(15), int64(1), object(9)
memory usage: 38.1+ MB

In [16]:
val= datos.sample(frac = 0.3)

In [17]:
nombre_fichero_validacion = 'validacion.csv'

ruta_completa = path + '/02_Datos/02_Validacion/' + nombre_fichero_validacion

val.to_csv(ruta_completa)

### Extraer y guardar dataset trabajo

In [18]:
trabajo = datos.loc[~datos.index.isin(val.index)]

In [19]:
nombre_fichero_trabajo = 'trabajo.csv'

ruta_completa = path + '/02_Datos/03_Trabajo/' + nombre_fichero_trabajo

trabajo.to_csv(ruta_completa)